- Classes/Managers/LocalAssetsManager.swift
- Classes/Player/AssetBuilder.swift
- Classes/Player/DefaultAssetHandler.swift
- Classes/Player/MediaEntry.swift
- Example/PlayKit.xcodeproj/project.pbxproj
- Example/Tests/SourceSelectorTest.swift
Source selection (in AssetBuilder) is now more explicit and less "generic", but it's also correct. The previous approach looks nice, but was not accurate.
> Source selection fixes

- Classes/Player/PKEvent.swift
- Classes/PlayerEvent.swift
- Plugins/IMA/IMAPlugin.swift
- Plugins/KalturaStats/KalturaStatsPlugin.swift
- Plugins/Phoenix/KalturaPluginManager.swift
- Plugins/Youbora/YouboraEvent.swift
fixed issues with project after events changes.
> Fixed issues after events changes.

- Classes/Managers/AppState/AppStateProvider.swift
- Classes/Managers/AppState/AppStateSubject.swift
- Classes/Managers/NotificationsManager.swift
- Classes/Player/AVPlayerEngine.swift
- Classes/Player/AssetLoaderDelegate.swift
- Plugins/Phoenix/KalturaPluginManager.swift
* Added fix for KalturaPluginManager to observe app termination event and send stop event.
* Added class for observing app state events and posting to observers named: AppStateSubject.
> FEM-1029 stop event on app terminate

- Classes/Managers/LocalAssetsManager.swift
- Classes/Player/Player.swift
- Classes/Player/PlayerConfig.swift
small enhancements **will not** effect public api
> Small enhancement to player config

- Classes/Player/AssetBuilder.swift
- Classes/Player/MediaEntry.swift
This includes source selector and playback, but not media provider.
> Support mp3 files

- Classes/PlayerEvent.swift
- Classes/Plugins/Ads/PKAdCuePoints.swift
- Plugins/IMA/IMAPlugin.swift
- Plugins/IMA/PKAdInfo.swift
* Added `AdPositionType` for getting the type of the ad position from the ad info event.
* Renamed `AdInfo` to `PKAdInfo` and also `AdCuePoints` to `PKAdCuePoints`.
> More information to AdInformation event

- Plugins/IMA/IMAPlugin.swift
> #FEM-1199 #comment fix setup ima loader issue

- Addons/GoogleCast/BasicCastBuilder.swift
> #FEM-1201 #comment expose CC StreamType to Obj-C

- Plugins/Youbora/YouboraEvent.swift
- Plugins/Youbora/YouboraPlugin.swift
renamed youbora event to report to align with other report events from kaltura analytics report event.
> Youbora report event

- Classes/Player/AVPlayerEngine/AVPlayerEngine+Observation.swift
- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
In addition to FEM-1302, added a check to compare last timebase rate, fixes an issue.
> Timebase event improvement

- PlayKit.podspec
Added missing supported version under libs:
- SwiftyJSON
- Log
- SwiftyXMLParser
- KalturaNetKit
- Youbora-AVPlayer
> Add supported version to Podspec dependencies

- Addons/GoogleCast/BasicCastBuilder.swift
- Addons/GoogleCast/CastAdInfoParser.swift
- Classes/Player/AssetLoaderDelegate.swift
- Classes/Player/Player.swift
- Classes/Player/PlayerDecoratorBase.swift
- Classes/Player/Track.swift
- Classes/Player/TracksManager.swift
- Classes/Providers/OTT/PhoenixMediaProvider.swift
- Plugins/Phoenix/PhoenixAnalyticsPlugin.swift
- Plugins/Phoenix/TVPAPIAnalyticsPlugin.swift
Fixed warnings in the project and aligned some issues.
> Warning Fixes

- Classes/Backend/OVP/Model/OVPLiveStreamEntry.swift
- Classes/Backend/OVP/Parsers/OVPObjectMapper.swift
* Fixed issue where ‘KalturaLiveStreamEntry’ wasn’t parsed. Added new OVPLiveStreamEntry.
> #FEM-1388 

- Plugins/Phoenix/BaseOTTAnalyticsPlugin.swift
avoid sending stop after finish
> FEM-1394 #comment avoid sending stop after finish - analytics

- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
- Classes/Player/Player.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerDecoratorBase.swift
- Classes/Player/PlayerView.swift
- Plugins/IMA/IMAPlugin.swift
* Updated `PlayerView` to have AVPlayerLayer backed in, instead of adding sub-layer.
* Update `Player.view` property to be of type `PlayerView`
* Added convenience method for player view to add inside container view easily.
> Player View Enhancements

- PlayKit.podspec
Update google cast SDK version to 3.5
Tested on cast sample:
https://github.com/kaltura/playkit-ios-samples/tree/master/ChromecastSample
> FEM-1428 #comment Update cast sdk from 3.3.0 to 3.5

- Classes/Player/Player.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerDecoratorBase.swift
- Classes/Player/PlayerLoader.swift
Expose single event registration
> FEM-1254 #comment Expose single event registration

- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
- Classes/Player/Player.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerDecoratorBase.swift
* Added player rate readonly property
> Player Rate

- Classes/Managers/AppState/AppStateProvider.swift
- Classes/Managers/AppState/AppStateSubject.swift
- Classes/Managers/NotificationsManager.swift
make AppStateProvider public and whole related classes
> FEM-1475 #comment make AppStateProvider public

- PlayKit.podspec
- Bump SwiftyXMLParser to fix xcode9 issue 
- (https://github.com/yahoojapan/SwiftyXMLParser/releases/tag/3.0.3)
> FEM-1503 #comment bump SwiftyXMLParser to fix xcode9 issue

- Classes/Player/AVPlayerEngine/AVPlayerEngine+Observation.swift
- Classes/Player/Player.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerDecoratorBase.swift
- Classes/PlayerState.swift
- Plugins/KalturaStats/KalturaStatsPlugin.swift
- Plugins/Phoenix/BaseOTTAnalyticsPlugin.swift
- Plugins/Youbora/YouboraManager.swift
- Replace `loading` event with `ended`
- Reflect current state property
- Remove isContentEnded Boolean
> FEM-1521, remove loading event & add ended event & state reflection

- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
- Classes/Player/BasicPlayer.swift
- Classes/Player/Player.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerDecoratorBase.swift
- Classes/Player/PlayerEngine.swift
* `PlayerEngine` protocol attachment
* `BasicPlayer` protocol attachment
> FEM-1569 #comment PlayerEngine attachment

- Classes/PKRequestParams.swift
- Classes/Player/PlayerController.swift
* Removed the word kaltura from the player.
* Fixed adapter updating.
> Addition to FEM-1585 fix

- Classes/Player/PlayerController.swift
* Activate refresh asset 
* Avoid refresh on reachable
> FEM-1603 #comment activate refresh asset & avoid refresh on reachable

- Classes/Player/AVPlayerEngine/AVPlayerEngine+AssetLoading.swift
- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
- Classes/Player/PKAsset.swift
- Classes/Player/PKPlayerSettings.swift
- Classes/Player/Player.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerDecoratorBase.swift
added `PKPlayerSettings` to hold all the player's settings.
added `preferredPeakBitRate` to network settings under player settings.
to set the preferred peak bit rate just do:
`player.settings.network.preferredPeakBitRate = your value`
> Preferred Peak Bitrate

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
* ISSUE_TEMPLATE
* PULL_REQUEST_TEMPLATE
> github PR & Issues template attachment

- Classes/Player/PlayerController.swift
- Widevine/WidevineClassicAssetHandler.swift
Fixed issue with widevine classic where same media would play twice when changing media.
> Widevine Classic Fix

- Classes/Backend/Base/FormatsHelper.swift
- Classes/Player/AssetBuilder.swift
- Classes/Player/MediaEntry.swift
> FEM-1659 #comment support mov files

- Classes/Player/AVPlayerEngine/AVPlayerEngine+TimeMonitor.swift
- Classes/Player/Player.swift
- Classes/Player/PlayerDecoratorBase.swift
* Remove all time observers is now internal.
* Added debug logs for time observation adding and removing.
> time observation fix

- Classes/PKError.swift
- Classes/Player/Decorators/PlayerDecoratorBase.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerLoader.swift
- Classes/Player/PlayerWrapper/AVPlayerWrapper.swift
- Classes/Player/Protocols/BasicPlayer.swift
* [FEM-1685],  remove throwable prepare
> FEM-1685 #comment remove throwable prepare

- Example/PlayKit.xcodeproj/project.pbxproj
- Example/Podfile.lock
- Example/Tests/Analytics/OTTAnalyticsPluginTest.swift
- Example/Tests/MessegeBusTest.swift
- Example/Tests/PlayerControllerTest.swift
- Example/Tests/PlayerCreator.swift
- Example/Tests/SourceSelectorTest.swift
> FEM-1695: fix compilation errors

- Classes/Player/Media/PKMediaEntry.swift
- Classes/Providers/OVP/SimpleOVPSessionProvider.swift
- Plugins/Youbora/YouboraPlugin.swift
Support some public methods of SDK in objc
> FEM-1701: expose PKMediaEntry constructor into objc

- PlayKit.podspec
Update podspec to point on latest version of youbora
> FEM-1705: update podspec

- Classes/Player/PlayerWrapper/AVPlayerWrapper.swift
resolve player release issue, `[weak self]` attachment in a block
> add weak self in a block

- Classes/Events/PlayerEvent.swift
- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
- Classes/Player/PKEvent.swift
- Classes/Player/Tracks/TracksManager.swift
On every track selection 'TrackSelected' event will be fired
> FEM-1713: 'track selected' event added

- Classes/Events/PlayerEvent.swift
- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
- Classes/Player/Media/PKMediaSource.swift
- Classes/Player/PKEvent.swift
- Example/PlayKit.xcodeproj/project.pbxproj
- Example/PlayKit.xcworkspace/contents.xcworkspacedata
- Example/Podfile.lock
- Example/Tests/SourceSelectorTest.swift
- Plugins/AnalyticsCommon/AnalyticsPluginProtocol.swift
- Plugins/AnalyticsCommon/BaseAnalyticsPlugin.swift
- Plugins/KalturaLiveStats/KalturaLiveStatsPlugin.swift
- Plugins/KalturaStats/KalturaStatsPlugin.swift
- Plugins/Phoenix/BaseOTTAnalyticsPlugin.swift
> FEM-1676 #comment changes for KAVA plugin

- Classes/Backend/Base/FormatsHelper.swift
- Classes/Managers/LocalAssetsManager.swift
- Classes/Player/Builders/AssetHandler.swift
- Classes/Player/Media/PKMediaSource.swift
- Classes/Player/Media/SourceSelector.swift
Reverts kaltura/playkit-ios#249
> Revert "Fem 1740"

- Addons/GoogleCast/BasicCastBuilder.swift
- Addons/GoogleCast/CastAdInfoParser.swift
- Addons/GoogleCast/OVPCastBuilder.swift
- Addons/GoogleCast/TVPAPICastBuilder.swift
- Classes/Events/EventsPayloads/PKAdInfo.swift
- Classes/Managers/LocalAssetsManager.swift
- Classes/Managers/TimeObserver.swift
- Classes/Models/PKBoundary.swift
- Classes/Models/PKTimeRange.swift
- Classes/PKRequestParams.swift
- Classes/Player/Media/PKMediaEntry.swift
- Classes/Player/Media/PKMediaSource.swift
- Classes/Player/Media/SourceSelector.swift
- Classes/Player/PKAsset.swift
- Classes/Player/PKController.swift
- Classes/Player/PKPlayerSettings.swift
- Classes/Player/PKVRController.swift
- Classes/Player/PlayerConfig.swift
- Classes/Player/PlayerController+TimeMonitor.swift
- Classes/Player/Tracks/TracksManager.swift
- Classes/Player/VR/VRData.swift
- Classes/Player/VR/VRPlayerEngine.swift
- Classes/Plugins/PKPlugin.swift
- Classes/Providers/Mock/MockMediaProvider.swift
- Classes/Providers/OVP/OVPMediaProvider.swift
- Classes/Providers/OVP/SimpleOVPSessionProvider.swift
- Classes/Providers/OVP/SourceBuilder.swift
- Plugins/AnalyticsCommon/AnalyticsPluginProtocol.swift
- Plugins/AnalyticsCommon/BaseAnalyticsPlugin.swift
Since swift4 is supported now all public API should have @objc attachment.
> FEM-1772 @objc attachment

- Classes/Player/AVPlayerEngine/AVPlayerEngine+Observation.swift
- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
- Classes/Player/PKPlayerSettings.swift
- Classes/Player/Tracks/TracksManager.swift
Added track selection settings.
> FEM-1741: Added track selection settings.

- Classes/Player/PlayerController.swift
Fixes an issue where a new wrapper was created for each prepare call. now if the wrapper type is the same only creates the first time.
> Wrapper Creation Fix

- Classes/Managers/TimeObserver.swift
- Classes/Player/AVPlayerEngine/AVPlayerEngine+Observation.swift
fixed issue with timebase when more than one player is working in parallel playing event would not work properly.
> timebase with multiple players fix

- Classes/Player/AVPlayerEngine/AVPlayerEngine+Observation.swift
Fixed issue with track selection, now check current track language code with canonicaldentifier
> tracks selection fix

- Classes/Player/PlayerController.swift
* fixed issue where current player was vr and changing to regular playback didn't change the player type.
> #FEM-1945 VR360 change media fix

- Classes/FairPlayDRM/FPSContentKeySessionDelegate.swift
- Classes/FairPlayDRM/FPSLicenseHelper.swift
Code clean up.
Retained self for future work.
> Crash fix, FPS in online mode.

- .travis.yml
- Classes/Managers/AppState/AppStateProvider.swift
- Classes/Managers/AppState/AppStateSubject.swift
- Classes/Managers/PlayKitManager.swift
- Classes/Managers/Reachability.swift
- Classes/Network/KalturaPlaybackRequestAdapter.swift
- Classes/Network/KalturaUDRMLicenseRequestAdapter.swift
- Classes/Player/Media/PKMediaSource.swift
- Classes/Player/VR/VRPlayerEngine.swift
- Classes/Providers/OTT/PhoenixMediaProvider.swift
- Classes/Providers/OVP/OVPMediaProvider.swift
- Example/PlayKit.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Changes for Swift 4.
Some documentation updates, fixing warnings.
> Fem 2123 Changes for Swift 4

- Classes/Backend/OTT/Model/OTTMediaAsset.swift
- Classes/Backend/OTT/Model/OTTMediaFile.swift
- Classes/Backend/OTT/Model/OTTMultilingualStringValue.swift
- Classes/Backend/OTT/Parsers/OTTObjectMapper.swift
- Classes/Backend/OTT/Services/OTTAssetService.swift
- Classes/Providers/OTT/PhoenixMediaProvider.swift
Added the request to get the asset.
Parsed the asset, as well as the metas, only string values for now.
Set the tags property on the PKMediaEntry with value tags from the metas.
> FEM-2191 Support 360 in OTT

- Classes/Player/AVPlayerEngine/AVPlayerEngine+Observation.swift
> FEM-2181 Xcode 10 fixes.

- Classes/Backend/OTT/Services/OTTAssetService.swift
- Classes/Providers/OTT/PhoenixMediaProvider.swift
'return' missing after callback upon error.
Code indentation.
Additional fixes and defaults updated.
> Additional fixes and defaults updated.

- Classes/FairPlayDRM/FPSAssetLoaderDelegate.swift
- Classes/FairPlayDRM/FPSUtils.swift
- Classes/Managers/AppState/AppStateSubject.swift
- Classes/Managers/LocalAssetsManager.swift
- Classes/Managers/LocalDataStore.swift
- Classes/Managers/PlayKitManager.swift
- Classes/MessageBus.swift
- Classes/PKLog.swift
- Classes/Player/AVPlayerEngine/AVPlayerEngine+Observation.swift
- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
- Classes/Player/Handlers/DefaultAssetHandler.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerLoader.swift
- Classes/Player/PlayerWrapper/AVPlayerWrapper.swift
- Classes/Player/PlayerWrapper/DefaultPlayerWrapper.swift
- Classes/Player/Tracks/PKTracks.swift
- Classes/Player/Tracks/Track.swift
- Classes/Player/Tracks/TracksManager.swift
- Classes/Plugins/BasePlugin.swift
- Example/Tests/Analytics/OTTAnalyticsPluginTest.swift
- PlayKit.podspec
- Plugins/AnalyticsCommon/BaseAnalyticsPlugin.swift
- Plugins/Phoenix/PhoenixAnalyticsPlugin.swift
- Plugins/Phoenix/TVPAPIAnalyticsPlugin.swift
- Widevine/WidevineClassicAssetHandler.swift
Our current logger (https://github.com/delba/Log) is broken in Swift 4.2 (Xcode 10) in a way that makes the log levels random.
Move to [XCGLogger](https://github.com/DaveWoodCom/XCGLogger).
> FEM-2229: Change logger to XCGLogger

- Addons/GoogleCast/BasicCastBuilder.swift
- Addons/GoogleCast/CAFCastBuilder.swift
- Addons/GoogleCast/OVPCastBuilder.swift
- Addons/GoogleCast/TVPAPICastBuilder.swift
- PlayKit.podspec
- TestApp/TestApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Implemented the new CAF Sender for v3 receiver.
Updated google-cast SDK to version 4.3.2.
> FEM-2103  Chrome cast implementation of the CAF Sender

- Classes/Events/AdEvent.swift
- Classes/Events/PlayerEvent.swift
- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
- Classes/Player/Decorators/PlayerDecoratorBase.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerWrapper/AVPlayerWrapper.swift
- Classes/Player/PlayerWrapper/DefaultPlayerWrapper.swift
- Classes/Player/Protocols/BasicPlayer.swift
Added replay function to the player.
Added missing events to the allEventTypes property.
> FEM-2194 Added replay function to the player.

- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerWrapper/AVPlayerWrapper.swift
- Classes/Player/PlayerWrapper/DefaultPlayerWrapper.swift
- Classes/Player/Protocols/PlayerEngine.swift
- PlayKit.podspec
Added playbackType property to get it back from the AVPlayerItem
Updated the podspec to have the new version format.
isLive function will check first with the currentPlayer playbackType if it's Live before checking with the mediaEntry mediaType.
> Fem 2308 - Phoenix Provider works with old API version - Need to upgrade in order to support KalturaLiveAsset

- Classes/Events/AdEvent.swift
Added an option to send the clickThroughUrl to the event data when creating the AdClicked event.
> FEM-2325 IMA Plugin - Add the clickThroughUrl to the AdClicked event

- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
- Classes/Player/Media/PKMediaEntry.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerWrapper/AVPlayerWrapper.swift
- Classes/Player/PlayerWrapper/DefaultPlayerWrapper.swift
- Classes/Player/Protocols/PlayerEngine.swift
Added MediaType dvrLive.
Updated isLive function to return true for live and dvrLive media type.
Added 'playFromLiveEdge' func.
Fixed the timescale to be as the rangeStart timescale for the newTime of the currentPosition.
> Fem 2341 Perform seek to live edge inside PlayKit upon Live media

- Classes/Events/EventsPayloads/PKAdInfo.swift
Added the following vastMediaWidth, vastMediaHeight and vast MediaBitrate to expose extra data from the ad.
Added description function, so that the data will be printed in the log in verbose log level.
> FEM-2316 Expose additional IMA ad data

- Classes/Managers/PlayKitManager.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerLoader.swift
Removed crash, the player will be created even if a plugin was not registered.
Removed crash if the media was set up as 360 but the VRPlayer plugin was not added, AVPlayer will be created.
> FEM-2080 Player should not crash if a configured plugin is not found

- Classes/Player/Media/PKMediaEntry.swift
Added name to the PKMediaEntry.
Fixed description to include all properties.
Added description to the MediaType enum.
> FEM-2250 Added name to the PKMediaEntry.

- Classes/Player/PlayerController.swift
Fixed resume function to perform playFromLiveEdge in case of a Live media.
> FEM-2341 Perform seek to live edge inside PlayKit upon Live media

- Classes/Events/PlayerEvent.swift
- Classes/Player/AVPlayerEngine/AVPlayerEngine+Observation.swift
Added AVPlayerItemPlaybackStalled as Stalled to the PlayerEvents.
> FEM-2322 Add AVPlayerItemPlaybackStalled to the PlayerEvents

- Classes/Player/Tracks/TracksManager.swift
Fixed text track to show the 'Name' of the metadata if exists.
> FEM-2346 Text track label is shown as unknown in some cases.

- Classes/Player/AVPlayerEngine/AVPlayerEngine+Observation.swift
- Classes/Player/PKPlayerSettings.swift
- Classes/Player/Tracks/TracksManager.swift
Added 'cea608CaptionsEnabled' to the player settings to enable or disable CLOSED-CAPTIONS in the text tracks.
> FEM-2376 Add cea608CaptionsEnabled to the PlayerSettings

- Classes/Events/EventsPayloads/PKAdInfo.swift
- Classes/PKLog.swift
- Classes/Player/Media/PKMediaEntry.swift
- Classes/Player/Media/PKMediaSource.swift
- Classes/Player/PKPlayerSettings.swift
- Classes/Player/PlayerState.swift
- Classes/Player/VR/VRPlayerEngine.swift
Added description to all enums via CustomStringConvertible.
> FEM-2371 Add CustomStringConvertible to all enums

- PlayKit.podspec
> Updated version to 3.8.0

- PlayKit.podspec
- TestApp/Podfile.lock
- TestApp/TestApp.xcodeproj/project.pbxproj
Updated KalturaNetKit min version to 1.0.0.
> FEM-2387 Updated KalturaNetKit min version to 1.0.0.

- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
Reverting back, so that calling play will start the player once it is ready.
> FEM-2451 Player doesn't start playing once ready

- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
Added a check so that seek can't be done over the duration nor below 0.
> FEM-2393 Cap seek target

- Classes/Player/Decorators/PlayerDecoratorBase.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerWrapper/AVPlayerWrapper.swift
- Classes/Player/PlayerWrapper/DefaultPlayerWrapper.swift
- Classes/Player/Protocols/BasicPlayer.swift
> FEM-2464 Expose player volume
