- Classes/Player/AVPlayerEngine.swift
- Example/PlayKit.xcodeproj/project.pbxproj
- Example/Tests/PlayerControllerTest.swift
* Fixed issue where pause event would fire even after media finished playing.
> FEM-1036, OTT Analytics: pause action displayed when media finished playing

- Classes/Managers/PlayKitManager.swift
- Classes/Player/PlayerConfig.swift
- Classes/Player/PlayerLoader.swift
- Example/Tests/MessegeBusTest.swift
- Example/Tests/PlayerControllerTest.swift
- Plugins/Phoenix/KalturaPluginManager.swift
* Separated `prepare()` function from load. to use player and start buffering immediately now using load + prepare separately.
* Added documentation.
first play issue was solved in FEM-1027
> FEM-1035 wrong actions on app launch

- Classes/Managers/PlayKitManager.swift
- Classes/MessageBus.swift
- Classes/Player/AVPlayerEngine.swift
- Classes/Player/MediaEntry.swift
- Classes/Player/Player.swift
- Classes/Player/PlayerConfig.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerDecoratorBase.swift
- Classes/Player/PlayerLoader.swift
- Classes/Plugins/Analytics/AnalyticsConfig.swift
- Classes/Plugins/PKPlugin.swift
- Plugins/IMA/IMAPlugin.swift
- Plugins/KalturaStats/KalturaStatsPlugin.swift
- Plugins/Phoenix/KalturaPluginManager.swift
- Plugins/Phoenix/PhoenixAnalyticsPlugin.swift
- Plugins/Phoenix/TVPAPIAnalyticsPlugin.swift
- Plugins/Youbora/YouboraManager.swift
- Plugins/Youbora/YouboraPlugin.swift
* changed PlayKitManager sharedInstance to shared in swift (in objective-c it is still sharedInstance), much more swifter.
* separated `PlayerConfig` to `MediaConfig` that will be used for preparing the player and `PluginConfig` that will be used for loading the player.
Also created a `PlayerConfig` object as a composition for `MediaConfig` and `PluginConfig`.
* changed player’s prepare to receive `MediaConfig` instead of player config.
* changed player duration from double to TimeInterval (time interval is also a double but make more sense for duration to be time related).
* `PlayerLoader` now loads the plugin media entry when prepare is called and loader.load method just initializes the plugin.
* PKPlugin was added `mediaEntry` property and `onLoad` + `onUpdateMedia` methods to enable …
> Config API change and PKPlugin

- Classes/Managers/PlayKitManager.swift
prevents initializing `PlayKitManager` from outside in swift and objc.
> Fix to prevent initializing `PlayKitManager` from outside 

- Classes/Managers/PlayKitManager.swift
- Classes/Player/AVPlayerEngine.swift
- Classes/Plugins/PKPlugin.swift
Fixes memory leak created by Apple’s interoperability for initializing object from protocol.Type with @objc attribute
> Fixes memory leak created by Apple’s interoperability

- Classes/Network/SessionProvider.swift
- Classes/Providers/MediaEntryProvider.swift
- Classes/Providers/Mock/MockMediaProvider.swift
- Classes/Providers/OTT/OTTMediaProvider.swift
- Classes/Providers/OTT/Session/OTTSessionManager.swift
- Classes/Providers/OVP/OVPMediaProvider.swift
- Classes/Providers/OVP/Session/OVPSessionManager.swift
- Classes/Providers/OVP/SimpleOVPSessionProvider.swift
Swift generics are incompatible with Objective-C, so the protocol methods:
```swift
func loadKS(completion: @escaping (_ result :Result<String>) -> Void)
func loadMedia(callback: @escaping (Result<MediaEntry>) -> Void)
```
Could not be translated to objc, which causes the entire protocol to be incompatible.
The fix is changing above methods to:
```swift
func loadKS(completion: @escaping (String?, Error?) -> Void)
func loadMedia(callback: @escaping (MediaEntry?, Error?) -> Void)
```
> Made SessionProviders and MediaEntryProviders objective-c compatible

- Classes/Managers/AppState/AppStateSubject.swift
- Classes/MessageBus.swift
- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
- Classes/Player/PlayerController.swift
* Added `DispatchQueue.main.async` calls to play, pause and destroy functions to make sure they are dealt with on main thread.
* Added fix to `AppStateSubject` observation.
* Removed `isDestroyed` flag from `AVPlayerEngine` - wasn’t necessary.
* Added comments and improved some logs.
> General improvements

- Classes/Managers/LocalAssetsManager.swift
A source with drmParams != nil but empty should be considered clear.
> Fixed getPreferredDownloadableMediaSource

- Classes/Player/PlayerController.swift
- Classes/PlayerEvent.swift
- Classes/WidevineClassicHelper.swift
- Widevine/WidevineClassicAssetHandler.swift
*  a semaphore attachment to make sure prepare calling will wait till assetToPrepare it set.
*  fix small warnings
> FEM-1438 #comment fix wvm support - assetToPrepare is missed

- Classes/Providers/MediaEntryProviderResponseDelegate.swift
- Classes/Providers/OTT/PhoenixMediaProvider.swift
Adding a way to listen to the response of the getPlaybackContext and other requests are being sent by the mediaEntryProvider
> Adding MediaProvider Response Listener

- Widevine/WidevineClassicAssetHandler.swift
* Widevine: No reason to make license URI validation when refreshing asset
> FEM-1603 #comment fix for offline mode

- Classes/Player/AVPlayerEngine/AVPlayerEngine+AssetLoading.swift
- Classes/Player/AVPlayerEngine/AVPlayerEngine+Observation.swift
- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerWrapper/AVPlayerWrapper.swift
- Classes/Player/Protocols/Player.swift
- Classes/Player/VR/VRPlayerEngine.swift
* `AVPlayerWrapper` is `open` now
* `AVPlayerEngine ` is `public` now
*  Fix `VRPlayerWrapper` reflection support
*  Add `shouldAddPlayerViewController` function to `PlayerDelegate` - Let the SDK user know when VR viewController is ready for attachment
* Remove `playerShouldPlayAd` function from `PlayerDelegate` - never been used
> FEM-1563 #comment NYT initial integration

- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
In some cases duration is nan and we don't want to return this value, can cause issues.
So in this cases 0 will be returned instead.
> Duration nan protection

- Classes/Managers/TimeObserver.swift
- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
- Classes/Player/Decorators/PlayerDecoratorBase.swift
- Classes/Player/PlayerController+TimeMonitor.swift
- Classes/Player/PlayerController.swift
- Classes/Player/PlayerWrapper/AVPlayerWrapper.swift
- Classes/Player/Protocols/BasicPlayer.swift
- Classes/Player/Protocols/Player.swift
* Move observation from player engine to PlayerController in order to have a more general design, time observation was made to be used by every player.
* Removed the ability to remove all periodic and boundary observers (only available for internal use).
> Time observation enhancements

- Classes/Player/Media/PKMediaSource.swift
* fixed issue where media format was constructed without the needed format type, now if no format was given tries to handle using the provided url.
> #FEM-1867 widevine classic wrong media format

- Classes/Network/KalturaUDRMLicenseRequestAdapter.swift
- Classes/Player/Media/AssetLoaderDelegate.swift
- Classes/Player/Media/PKMediaEntry.swift
- Classes/Player/PKPlayerSettings.swift
- Classes/Player/PlayerController.swift
After calling loadPlayer(), the application can now call:
KalturaUDRMLicenseRequestAdapter.install(in: player, withAppName: "myapp.com")
This will set the referrer on license requests.
> Add KalturaUDRMLicenseRequestAdapter

- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
CurrentPosition of the player returns a negative value when the player hasn't started and on live streaming when seeking all the way back.
In no case it should be negative therefore, in such case, returning 0.
> FEM-2067 Fix for currentPosition returning a negative value.

- Plugins/Youbora/PKYouboraAdsAdapter.swift
- Plugins/Youbora/PKYouboraPlayerAdapter.swift
- Plugins/Youbora/YouboraPlugin.swift
This pull request fixes issues from QA report:
24,73,115,130,234
Short description of the changes:
- Ad adapter was not listening to AdClick event, so it was never fired
- fireJoin and fireBufferEnd are now fired regardless if it's a first play or not
- Now all errors are fatal, that means that any error will send /stop with it
- Small change to avoid a potential problem for not stoping adsAdapter before adapter
> Fix for Issues for QA report iteration #1

- Classes/Backend/OTT/Model/OTTMediaAsset.swift
- Classes/Backend/OTT/Parsers/OTTObjectMapper.swift
- Classes/Backend/OTT/Services/OTTAssetService.swift
- Classes/Backend/OTT/Services/PhoenixAPIDefines.swift
- Classes/Providers/OTT/PhoenixMediaProvider.swift
- `asset.get` was using the value of `assetType` as input to `assetReferenceType`, which is wrong: it happens to work when `assetType` is `media`. But when it's `epg` the value of `assetReferenceType` has to be either `epg_internal` or `epg_external`. Added it as a provider property.
- The response for `asset.get` when the type is `epg*` is `KalturaProgramAsset`. This type wasn't handled. Changed so that it's handled by `OTTMediaAsset`, which also handles `KalturaMediaAsset`.
> FEM-2219: Add and handle assetReferenceType as a parameter in PhoenixMediaProvider

- Classes/Managers/TimeObserver.swift
- Classes/Player/PlayerController.swift
TimeObserver now has an `enabled` property, defaults to false. When set to true (by `PlayerController`) it starts the timer (if required).
> Only enable TimeObserver after a PlayerEngine is created

- Plugins/Phoenix/BaseOTTAnalyticsPlugin.swift
Should only be sent upon PlayerEvent.ended.
> FEM-2248 Finish Bookmark sent twice

- Classes/Player/AVPlayerEngine/AVPlayerEngine.swift
Removed unowned self in callback function, to prevent a crash when the player was deallocated.
Improved code when returning to foreground, before the timer has been fired, to end the background task.
Improved code invalidated the timer when arriving from the expirationHandler, to prevent firing the timer.
> FEM-2278 Crash upon going to the background in some cases.

- Classes/Managers/PlayKitManager.swift
- Classes/Plugins/BasePlugin.swift
- Classes/Plugins/PKPlugin.swift
The default implementation uses the version from info.plist, which is typically generated by Cocoapods.
> FEM-2258: Add `pluginVersion` to `PKPlugin` protocol

- Classes/Player/PlayerWrapper/AVPlayerWrapper.swift
Removed calling the PKEvent namespace, to prevent leak.
> FEM-2340 Removed calling the PKEvent namespace, to prevent leak.

- Classes/Player/AVPlayerEngine/AVPlayerEngine+Observation.swift
There is no off state for audio tracks, it should default to auto.
> FEM-2463 Audio track language isn't added to KAVA view events at beginning

- Classes/Events/EventsPayloads/PKAdInfo.swift
This is an enhancement to pass both the Creative ID and AdvertiserName from the Google Interactive Media Ads SDK through to PlayKit. There is a corresponding PR for the PlayKit IMA library that adds a similar change to the IMAExtensions.swift file allowing PKAdInfo to be constructed from a Google IMAAd object.
- [*] changes have been done against master branch, and PR does not conflict
- [*] new unit / functional tests have been added (whenever applicable)
None needed in my opinion.
- [*] test are passing in local environment 
No tests added for this.
- [*] Travis tests are passing (or test results are not worse than on master branch :))
- [*] Docs have been updated
There isn't much to do here since this is simply updating a property
> Expose Creative ID and Advertiser Name

- Classes/Player/Tracks/TracksManager.swift
Fixed audio track crash, the mediaType returned from the option of audible tracks has changed.
> FEM-2475 - The player crashes when trying to change audio tracks
